### ISSUE TITLE
Clarity needed (in a comment) for acctz RecordRequest keepalives

### ISSUE THREAD

**Issue by haussli** [openconfig/gnsi#137]
Since the keepalives are not ACKs of any sort, clarity should be added about the timestamp in the KA RecordRequest.
What should it be set to?
Should the server ignore it?  Else what is the behavior?  If it is ignored, how does a client stop the stream and restart it from a particular timestamp.
Also reference issues/77

**Comment by morrowc** [comment]
Oh, this is a good point. I believe in initial thoughts about this we had defined a keep-alive proto/packet... but were dissuaded from that path for reasons which aren't in my memory banks today :(  I think minus the keepalive officially being a packet/message, you can certainly just heartbeat requests on a reasonable timer.

It seems likely that in some deployments you may go quite some time between 'changes' on devices, so your heartbeats may just not get returned data for long intervals of time. Decisions about: "is this connection dead? Is the far end overworked and can't reply, but still there??"  seem like they get fixed at the TCP layer, mostly. It would be unfortunate if the client here decided after N no-replies to bounce the session, that is unnecessary work on the overall system, and possibly a confusing behavior :(

I think some thought/guidance on the system here is in order... I suspect that at least the idea that:
  0) start session, ask for <client configured> history be requested ("hi, give me everything since 27 days ago!")
  1) delivery from server -> client of the backlog avaialble
  2) sending of 'record request' with timestamp=record-received-timestamp
  3) process replies if any are received
  4) goto 2

is a good starting point, for me anyway, in the discussion.

**Comment by nmahabaleshwar** [comment]
I think in the current proposal there is no difference between a keep-alive and request message asking for records. Atleast the server treats every `RecordRequest` message as `The client is asking something, let me check if I have something to be sent`, it sends RecordResponses if there is any new event which happened after the timestamp in the message. It also uses this message as an indication that the client is still alive and consuming records. As @morrowc mentioned, some of the concerns about the liveness of the far-end can be handled by TCP so I am not sure if we need an application level keep-alive mechanism.

**Comment by morrowc** [comment]
It's almost certainly the case that I imagined this service in a totally incorrect manner :(
(this is probably where my original keep-alive type handling was supposed to be happening... that's since morphed)

Ok, so originally I viewed this as:
  1) client connects to the server/device and asks for accounting records from at least time-X.
  2) server/device sends all records in bunch (how that happens on the wire isn't important to me).
  3) server/device keeps on sending new logs as they are created
  4) the client was responsible to say periodically: "Still here!!" (keep-alive behavior)

Marcus, I think, dissuaded me from the keepalive method/thought process, effectively saying: "Hey, we have TCP keepalives, no worries!"

Now we believe/built a world where we are thinking the client will periodically tell the server/device: "Hey, since X more logs pls!"

I think that change is 'wrong thinking' on my part ;( If we agree on that (which would be awesome) then we just need to sort out expectations. I think the comment thread here says:

  "Client connects, asks for history, Device streams records from history and then just sends records as the are created forever... if TCP timeouts happen go to the start"
  
  That sounds, to me like the right thing, that a 'keep alive' application level function isn't necessary.
  
  Now, how do we fix the documentation ? :)

**Comment by haussli** [comment]
I agree! 
An implementation might also reset the session if the output queue remains full for too long (the "zero window" problem).  That covers TCP remaining connect, but the remote being dead.  also see ietf draft-chen-idr-tcp-user-timeout.

**Comment by nmahabaleshwar** [comment]
We are fine with this approach, can we close this issue ? We can raise a PR to update the documentation.

**Comment by haussli** [comment]
Please review https://github.com/openconfig/gnsi/pull/148 to address this behavioral change.  TiA
